### ISSUE TITLE
App doesn't work on Android 14

### ISSUE THREAD

**Issue by Saman-Izadi** [MlgmXyysd/GooTool#4]
It used to work on Android 13, but after an update it gives me this error 
![Screenshot_20231228_214730_Package installer](https://github.com/MlgmXyysd/GooTool/assets/85870077/4233af18-9043-494c-9c56-1dd1b1da9c85)
Tried reinstalling, didn't work, app has all permissions.

**Comment by MlgmXyysd** [comment]
Android 14 doesn't allow install apps that `targetSdkVersion` below 23 lol

You can use terminal to install: `adb / pm install --bypass-low-target-sdk-block FILENAME.apk` or modify targetSdkVersion in **WoG Classic**'s (not GooTool) AndroidManifest.xml

**Comment by Saman-Izadi** [comment]
Alright, You have to use `--bypass-low-target-sdk-block`, You can't change AndroidManifest.xml to a target SDK above 20, the game crashes, I guess that's what I can do for now

**Comment by pokemonfanx23-code** [comment]
What terminal?
